# Generated by Django 5.1.4 on 2025-01-02 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PROJfiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceCapture',
        ),
        migrations.DeleteModel(
            name='VoiceRecording',
        ),
    ]
